### ISSUE TITLE
Telescope looks ugly

### ISSUE THREAD

**Issue by MaxVerevkin** [RRethy/nvim-base16#40] opened 2022-03-13 17:43 UTC
Of course, this is a matter of personal preference, but I really think telescope used to look better.

## Before

![image](https://user-images.githubusercontent.com/34583604/158072074-62187b27-ab2e-441c-9314-a53b90bf49aa.png)

## After ffee7e0a78a6519b81ea9f2addab64f3dadaae33 and ca3ee8343118c53b8bad02d96466be2417f1f855

![image](https://user-images.githubusercontent.com/34583604/158072092-215fd885-22dd-44fa-ba9d-69c41d4cab39.png)

**Comment by RRethy** [comment] 2022-03-13 19:43
Duplicate of #32, but I'll add an option to override. You can add this **before** loading the colorscheme.

```lua
require('base16-colorscheme').with_config {
    telescope = false,
}
```

**Closed by RRethy** 2022-03-13 19:44 UTC

**Comment by MaxVerevkin** [comment] 2022-03-13 19:51
> ```lua
> require('base16-colorscheme').with_config {
>     telescope = false,
> }
> ```

Thanks :)
