### ISSUE TITLE
Telescope weird appearance

### ISSUE THREAD

**Issue by SimonMandlik** [RRethy/nvim-base16#37] opened 2022-02-05 15:07 UTC
Commit https://github.com/RRethy/nvim-base16/commit/ca3ee8343118c53b8bad02d96466be2417f1f855 broke telescope appearance for me:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/16707112/152647245-c436f899-1109-4d3c-9c97-6416d3048317.png">

`minimal.lua`:

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        'RRethy/nvim-base16',
        requires = {
          'nvim-lua/plenary.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  vim.cmd('colorscheme base16-3024')
  require('telescope').setup{}
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

This is how it looks like without base16:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/16707112/152647286-74212667-2cfa-49e0-b741-439d9529454c.png">

**Comment by RRethy** [comment] 2022-02-05 16:55
Duplicate of #32

**Closed by RRethy** 2022-02-05 16:55 UTC
